# Generated by Django 4.2.4 on 2023-12-09 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('coleccion', models.CharField(choices=[('curandera', 'Curandera')], default='curandera', max_length=20)),
                ('foto', models.ImageField(blank=True, default='fotos_productos/default.png', null=True, upload_to='fotos_productos')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=16)),
                ('rol', models.CharField(choices=[('administrador', 'Administrador'), ('usuario', 'Usuario')], default='usuario', max_length=20)),
            ],
        ),
    ]
